spring:
  datasource:
    url: postgresql://postgres:abvmWGOYFKAINCMmJyELZhXCbFRxnvcZ@viaduct.proxy.rlwy.net:40977/railway
    username: postgres
    password: abvmWGOYFKAINCMmJyELZhXCbFRxnvcZ
    host: viaduct.proxy.rlwy.net
    port: 40977
    name: railway

#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes
